spring.application.name=CustomerOrder

server.port = 8080

spring.datasource.url=jdbc:postgresql://localhost:5432/demo
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Log into a file
logging.file.name=logs/customer-order.log

# Optional: logging pattern
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Optional: logging level
logging.level.root=INFO
logging.level.com.yourpackage=DEBUG

Service.CUSTOMER_NOT_FOUND = No Customer Found with given Customer Id
Service.CUSTOMERS_NOT_FOUND = No customers found
Service.ORDER_NOT_FOUND = No Order Found
General.EXEPTION_MESSAGE = Request could not be processed due to some issue. Please try again!!
API.INSERT_SUCESS = Customer added successfully
API.UPDATE_SUCESS = Customer updated successfully.
API.DELETE_SUCESS = Customer details deleted successfully.

API.ORDER_INSERT_SUCESS = Order placed successfully
API.ORDER_UPDATE_SUCESS = Order updated successfully.
API.ORDER_DELETE_SUCESS = Order cancelled successfully.
